USE DATABASE CRICKET;
USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE SCHEMA IF NOT EXISTS CRICKET.GOLD;
USE SCHEMA CRICKET.GOLD;

-- PLAYER VIEW
CREATE OR REPLACE VIEW PLAYER AS
SELECT
    MATCH_TYPE_NUMBER,
    COUNTRY,
    PLAYER_NAME
FROM CRICKET.SILVER.PLAYER_CLEAN;

-- DELIVERY VIEW 
CREATE OR REPLACE VIEW DELIVERY AS
SELECT
    MATCH_TYPE_NUMBER,
    TEAM_NAME,
    OVER,
    BOWLER,
    BATTER,
    NON_STRIKER,

    RUNS,
    EXTRAS,
    TOTAL,
    EXTRA_TYPE,

    PLAYER_OUT,
    PLAYER_OUT_KIND,
    PLAYER_OUT_FIELDER,

    REVIEW_BY_TEAM,
    REVIEW_DECISION,
    REVIEW_TYPE,

FROM CRICKET.SILVER.DELIVERY_CLEAN;

-- MATCH VIEW
CREATE OR REPLACE VIEW MATCH AS
SELECT
    MATCH_TYPE_NUMBER,
    EVENT_NAME,
    MATCH_NUMBER,
    EVENT_DATE,
    EVENT_YEAR,
    EVENT_MONTH,
    EVENT_DAY,

    MATCH_TYPE,
    SEASON,
    TEAM_TYPE,
    OVERS,

    CITY,
    VENUE,
    GENDER,

    FIRST_TEAM,
    SECOND_TEAM,
    WINNER,

    WON_BY_RUNS,
    WON_BY_WICKETS,

    PLAYER_OF_MATCH,

    MATCH_REFEREE,
    RESERVE_UMPIRES,
    TV_UMPIRES,
    FIRST_UMPIRE,
    SECOND_UMPIRE,

    TOSS_WINNER,
    TOSS_DECISION

FROM CRICKET.SILVER.MATCH_CLEAN;